---
driver:
  name: vagrant
  network:
    - - forwarded_port
      - guest: 80
        host: 8880
        auto_correct: true
    - - forwarded_port
      - guest: 443
        host: 8443
        auto_correct: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0
  data_bags_path: 'test/integration/data_bags'

platforms:
- name: ubuntu-14.04
  driver:
    box: bento/ubuntu-14.04

suites:
- name: default
  run_list:
    - recipe[askbot::pgsql_install]
    - recipe[askbot::deploy]
    - recipe[askbot::web]
    #- recipe[askbot::search]
    #- recipe[askbot::mathjax]
  attributes:
  excludes:
    - centos-6.6
    - centos-6.7
    - win2008
    - win2012
