---
driver:
  name: vagrant
  network:
    - - forwarded_port
      - guest: 80
        host: 8880
        auto_correct: true
    - - forwarded_port
      - guest: 443
        host: 8443
        auto_correct: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0
  data_bags_path: 'test/fixtures/data_bags'

platforms:
- name: ubuntu-14.04
  driver:
    box: bento/ubuntu-14.04

suites:
- name: default
  run_list:
    - recipe[apt]
    #- recipe[askbot]
    - recipe[askbot::pgsql_install]
    - recipe[askbot::database]
    - recipe[askbot::web]
    # - recipe[askbot::search]
    - recipe[askbot::deploy]
    # - recipe[askbot::mathjax]
  attributes:
    apt:
      compile_time_update: true