name             'askbot'
maintainer       'Dimension Data Cloud Solutions, Inc.'
maintainer_email 'eugene.narciso@itaas.dimensiondata.com'
license          'All Rights Reserved'
description      'Installs/Configures Q&A system askbot'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.0'

supports         'ubuntu'

depends 'python'
depends 'git'
depends 'postgresql'
depends 'apache2'
depends 'logrotate'
depends 'java'
depends 'ark'
depends 'database'
depends 'chef-vault'
depends 'yum'
depends 'apt'
depends 'didata-base'
