name             'askbot'
maintainer       'Dimension Data Cloud Solutions, Inc.'
maintainer_email 'eugene.narciso@itaas.dimensiondata.com'
license          'All Rights Reserved'
description      'Installs/Configures Q&A system askbot'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

supports         'ubuntu'

depends          'python', '~> 1.4.6'
depends          'git', '~> 4.3.7'
depends          'postgresql', '~> 4.0.0'
depends          'apache2', '~> 3.1.0'
depends          'logrotate', '~> 1.9.2'
depends          'java', '~> 1.39.0'
depends          'ark', '~> 1.0.0'
depends          'database', '~> 4.0.9'
depends          'solr', '~> 0.5.0'
depends          'chef-vault', '~> 1.3.2'
depends          'yum', '~> 3.10.0'
depends          'apt', '~> 2.9.2'
